# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  env:
    BROWSERSTACK: $(BROWSERSTACK)
    BROWSERSTACK_PWD: $(BROWSERSTACK_PWD)
    BROWSERSTACK_USER: $(BROWSERSTACK_USER)
    CONNECTION_STRING: $(CONNECTION_STRING)
    FROM_MONTH: $(FROM_MONTH)
    FROM_YEAR: $(FROM_YEAR)
    TO_MONTH: $(TO_MONTH)
    TO_YEAR: $(TO_YEAR)
    STRAVA_USER: $(STRAVA_USER)
    STRAVA_PWD: $(STRAVA_PWD)
  inputs:
    command: 'run'
    projects: '**/*.csproj'
    arguments: '144100'
