# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

# https://github.com/dotnet/cli/issues/8368#issuecomment-424852996
# https://github.com/ignatandrei/stankins/blob/master/azure-pipelines.yml
- script: |
    cd Prototype
    dotnet tool install  --tool-path . dotnet-ef
    ./dotnet-ef --project ./Prototype.csproj migrations add InitialCreate
    ./dotnet-ef --project ./Prototype.csproj database update
    ls
  displayName: 'call entity framework create and update'

- task: DotNetCoreCLI@2
  env:
    BROWSERSTACK: $(BROWSERSTACK)
    BROWSERSTACK_PWD: $(BROWSERSTACK_PWD)
    BROWSERSTACK_USER: $(BROWSERSTACK_USER)
    CONNECTION_STRING: $(CONNECTION_STRING)
    FROM_MONTH: 01
    FROM_YEAR: 2000
    TO_MONTH: 12
    TO_YEAR: 2019
    STRAVA_USER: $(STRAVA_USER)
    STRAVA_PWD: $(STRAVA_PWD)
  inputs:
    command: 'run'
    projects: '**/*.csproj'
    arguments: '144100'
