# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: Docker@2
  inputs:
    containerRegistry: 'GitHub Registry'
    repository: 'strava-x-api'
    command: 'buildAndPush'
    Dockerfile: '**/Prototype.Dockerfile'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

# https://github.com/dotnet/cli/issues/8368#issuecomment-424852996
# https://github.com/ignatandrei/stankins/blob/master/azure-pipelines.yml
- script: |
    cd Prototype
    dotnet tool install --tool-path . dotnet-ef  --version 3.0.0
    ./dotnet-ef --project ./Prototype.csproj migrations add InitialCreate
    ./dotnet-ef --project ./Prototype.csproj database update
    ls -alrt
  displayName: 'EF: create local db'
# retrieve db stats
- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    # path is relative to project path, before the workingDirectory ist evaluated
    projects: '**/*.csproj'
    arguments: '-c=stats'
    workingDirectory: 'Prototype/'
# call API
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops
- task: DotNetCoreCLI@2
  env:
    # values overwritten from pipeline variables
    BROWSERSTACK: $(BROWSERSTACK)
    BROWSERSTACK_PWD: $(BROWSERSTACK_PWD)
    BROWSERSTACK_USER: $(BROWSERSTACK_USER)
    CONNECTION_STRING: $(CONNECTION_STRING)
    FROM_MONTH: 01
    FROM_YEAR: 2019
    TO_MONTH: 12
    TO_YEAR: 2019
    STRAVA_USER: $(STRAVA_USER)
    STRAVA_PWD: $(STRAVA_PWD)
  inputs:
    command: 'run'
    # path is relative to project path, before the workingDirectory ist evaluated
    projects: '**/*.csproj'
    arguments: '-- -c=get-activities -athleteid=144100'
    workingDirectory: 'Prototype/'
# retrieve db stats
- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    # path is relative to project path, before the workingDirectory ist evaluated
    projects: '**/*.csproj'
    arguments: '-c=stats'
    workingDirectory: 'Prototype/'
