name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: cnrun/strava-x-api/strava-x-api
        username: ""
        password: ${{ secrets.GITHUB_TOKEN }}
